# -*- coding: utf-8 -*-
"""5.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNvu8eW87S-ocziIeeflKVXuoUr8WvUC
"""

import pandas as pd
#!pip install -U pandasql
import pandasql

dataf = pd.read_csv('nuforc.csv')

del dataf['Unnamed: 0'] #Eliminando a coluna desnecessária

"""###Quantidade de linhas do CSV"""

qtd_linhas = dataf['Date / Time'].size

"""###Relatos por Estado em ordem decrescente & removendo os NaN"""

st = """
    SELECT State, COUNT(State) as cState FROM dataf WHERE State != ' ' GROUP BY State ORDER BY cState desc;
  """
sql = pandasql.sqldf(st)

"""###Apenas dados dos EUA"""

lista_usa = ['AK','AL','AR','AZ','CA','CO','CT','DE','FL','GA',
             'HI','IA','ID','IL','IN','KS','KY','LA','MA','MD',
             'ME','MI','MN','MO','MS','MT','NC','ND','NE','NH',
             'NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC',
             'SD','TN','TX','UT','VA','VT','WA','WI','WV','WY']

lista = pd.DataFrame(lista_usa, columns=['Estados_EUA'])

sql_usa = """
  SELECT dataf.* FROM dataf, lista
  WHERE State = Estados_EUA
"""

separados_usa = pandasql.sqldf(sql_usa, locals())

"""###Quais cidades com mais relatos com no mínimo 10 relatos"""

cidades1 = """
    SELECT *, COUNT(*) as total_posts FROM separados_usa  GROUP BY City;
  """
sql_cidades1 = pandasql.sqldf(cidades1)

cidadesusa = """
    SELECT * FROM sql_cidades1 WHERE City != 'unknown' AND total_posts >= 10 ORDER BY total_posts desc;
    """
sql_cidadesusa = pandasql.sqldf(cidadesusa)

"""###Fazer uma query exclusiva para o estado com maior número de relatos, buscando cidades que possuam um número superior a 10 relatórios. Enfatizar a cidade, a quantidade de relatos e formato do objeto não identificado."""

estados1 = """
    SELECT State, MAX(cState) as maxState FROM sql;
  """
sql_estados1 = pandasql.sqldf(estados1)


#Essa query retorna uma tabela COM os campos vazios e desconhecidos(unknoun)
# estados2 = """
#     SELECT sql_cidadesusa.City, sql_cidadesusa.Shape, sql_cidadesusa.total_posts
#     FROM sql_cidadesusa, sql_estados1
#     WHERE sql_cidadesusa.State = sql_estados1.State AND total_posts > 10;
#   """
# sql_estados2 = pandasql.sqldf(estados2)


#Essa query retorna uma tabela SEM os campos vazios e desconhecidos(unknoun)
estados3 = """
    SELECT sql_cidadesusa.City, sql_cidadesusa.Shape, sql_cidadesusa.total_posts
    FROM sql_cidadesusa, sql_estados1
    WHERE (sql_cidadesusa.Shape != ' ' AND sql_cidadesusa.Shape != 'Unknown')  AND (sql_cidadesusa.State = sql_estados1.State AND total_posts > 10);
  """
sql_estados3 = pandasql.sqldf(estados3)