# -*- coding: utf-8 -*-
"""5.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdXgCtTcbmIWrcoMbl0adVs1zz7P2iOS

##MODO 01
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import time

total_df = []

for i in range (199709, 201709):
  i = str(i)
  abc = i[-2:]
  if not abc == '00' and int(abc) <= 12:
    req = requests.get('http://www.nuforc.org/webreports/ndxe'+ i +'.html')
    reqt = req.text
    soup = BeautifulSoup(reqt, 'html.parser')
    table = soup.find_all(name ='table')
    table_str = str(table)
    df = pd.read_html(table_str)[0]
    total_df.append(df)
    time.sleep(1)

df_total = pd.concat(total_df, ignore_index=True) 

df_total.to_csv('nuforc.csv')